### ISSUE TITLE
There are garbled characters when using Chinese, please help to fix it.

### ISSUE THREAD

**Issue by pczbq806** [SinuXVR/xDuoo-X3II-custom-firmware#2]
There are garbled characters when using Chinese, please help to fix it.

**Comment by SinuXVR** [comment]
Hi, try this, please: [chinese_font_update.upt](https://github.com/SinuXVR/xDuoo-X3II-custom-firmware/blob/master/chinese_font_update.upt)
Don't forget to rename it to _update.upt_ before install
